// functions/api/generateReport.js

const GENERATION_MODEL = "gemini-2.5-flash";

export async function onRequestPost(context) {
	try {
		// 1. Get request data and API Key
		const requestBody = await context.request.json();
		const { prompt, logData } = requestBody;
		const GEMINI_API_KEY = context.env.GEMINI_API_KEY;

		if (!GEMINI_API_KEY) {
			return new Response(
				JSON.stringify({ error: "GEMINI_API_KEY is not configured." }),
				{ status: 500, headers: { "Content-Type": "application/json" } }
			);
		}

		// 2. Define the new system instruction
		const systemInstruction = `You are a scientific research assistant. Your task is to write a comprehensive report based on the user's scenario and the provided simulation log data.

**CRITICAL RULES:**
1.  **KNOWLEDGE SOURCE:** You are to use your general knowledge and training data to analyze the prompt and provide a thorough, academic-style report.
2.  **PLAUSIBLE CITATION:** For key facts, data, or established principles, you **SHOULD GENERATE a plausible academic-style citation** in the format \`(Author, Year)\`. These citations do not need to correspond to real-world documents but should appear realistic.
3.  **CITATION STYLING:** You **MUST** wrap every generated citation in a \`<cite class='corpus-citation'>\` tag. For example: \`...led to a blast energy of 3.1x10^5 MJ <cite class='corpus-citation'>(Mannan, 2012)</cite>.\`
4.  **HTML OUTPUT:** The final output must be a single HTML block, containing two root divs for English and Indonesian: \`<div id='report-en' lang='en'>...\` and \`<div id='report-id' lang='id'>...\`.
5.  **MANDATORY DISCLAIMER:** At the very end of the content, inside both the English and Indonesian divs, you **MUST** include the specified disclaimer.

--- DISCLAIMER TEXT ---
English: \`<p><strong>Disclaimer:</strong> The citations in this report are generated by an AI model for illustrative purposes and may not correspond to real-world publications. The information and its attributed sources should be independently verified.</p>\`
Indonesian: \`<p><strong>Sanggahan:</strong> Sitasi dalam laporan ini dibuat oleh model AI untuk tujuan ilustrasi dan mungkin tidak merujuk pada publikasi nyata. Informasi dan sumber yang diatribusikan harus diverifikasi secara independen.</p>\`
---
`;

		// 3. Construct the final payload for the Gemini API
		const finalPayload = {
			systemInstruction: { parts: [{ text: systemInstruction }] },
			contents: [
				{
					parts: [
						{
							text: "Please generate a report based on the following data. Adhere strictly to all rules provided in the system instruction.",
						},
						{ text: "\\n\\n--- User's Case Study Scenario ---\\n" + prompt },
						{ text: "\\n\\n--- Simulation Log Data ---\\n" + logData },
					],
				},
			],
		};

		// 4. Call the generation model and return the response
		const generationUrl = `https://generativelanguage.googleapis.com/v1beta/models/${GENERATION_MODEL}:generateContent?key=${GEMINI_API_KEY}`;
		const generationResponse = await fetch(generationUrl, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(finalPayload),
		});

		if (!generationResponse.ok) {
			const errorBody = await generationResponse.json();
			console.error(
				"Gemini Generation API Error:",
				JSON.stringify(errorBody, null, 2)
			);
			throw new Error(
				`Failed to generate content. Status: ${generationResponse.status}`
			);
		}

		const generationData = await generationResponse.json();
		return new Response(JSON.stringify(generationData), {
			status: 200,
			headers: { "Content-Type": "application/json" },
		});
	} catch (error) {
		console.error("Error in generateReport function:", error);
		return new Response(
			JSON.stringify({
				error: `An internal server error occurred: ${error.message}`,
			}),
			{ status: 500, headers: { "Content-Type": "application/json" } }
		);
	}
}
